// Code generated by MockGen. DO NOT EDIT.
// Source: application/usecase/finance/usecase.go
//
// Generated by this command:
//
//	mockgen -source=application/usecase/finance/usecase.go -destination=application/usecase/finance/mock_usecase.go
//

// Package mock_finance is a generated GoMock package.
package finance

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// SimulateAnnualInvestment mocks base method.
func (m *MockUsecase) SimulateAnnualInvestment(a, p int, r float64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SimulateAnnualInvestment", a, p, r)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SimulateAnnualInvestment indicates an expected call of SimulateAnnualInvestment.
func (mr *MockUsecaseMockRecorder) SimulateAnnualInvestment(a, p, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SimulateAnnualInvestment", reflect.TypeOf((*MockUsecase)(nil).SimulateAnnualInvestment), a, p, r)
}
