// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package finance

import (
	"go-app/application/internal/domain/service"
)

// Injectors from wire.go:

func InitializeUsecase() Usecase {
	financeService := service.NewFinanceService()
	financeUsecase := NewUsecase(financeService)
	return financeUsecase
}
