// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-app/application/investment"
	"go-app/domain/service"
)

// Injectors from wire.go:

func initializeInvestmentUsecase() investment.Usecase {
	periodicInvestmentService := service.NewPeriodicInvestmentService()
	usecase := investment.NewUsecase(periodicInvestmentService)
	return usecase
}
