// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-app/application/domain"
	"go-app/application/usecase/finance"
)

// Injectors from wire.go:

func initializeFinanceUsecase() finance.Usecase {
	financeService := domain.NewFinanceService()
	usecase := finance.NewUsecase(financeService)
	return usecase
}
